#!/usr/bin/bash

# This script will overwrite your previous ~/.vimrc and ~/.vim
# Only proceed if this is desired


#### variables
VIMDIR=~/.vim
VIMRC=~/.vimrc
WORKINGDIR=`pwd`
useOffline=false


# Helper functions


function usage {
  echo "Usage: ./install [--offline]"
  echo "Desc: installs vim-config"
  echo "use --offline if you don't have access to the github repo"
}
# Process args
for i in "$@"
do
  case $i in
    -h | --help)
      usage
      exit 0
      shift
      ;;
    --offline)
      useOffline=true
      shift
      ;;
    *)
      echo "Error: unknown option <$1>"
      exit 1
      ;;
  esac
  shift
done

### Main code body

echo '____  ____   ___  ____  _  _  _  _   __   __ _    _  _  _  __  _  _        ___  __   __ _  ____  __  ___ '
echo '(  _ \(  _ \ / __)(  _ \( \/ )( \/ ) / _\ (  ( \  / )/ )( \(  )( \/ ) ___  / __)/  \ (  ( \(  __)(  )/ __)'
echo ' ) __/ )   /( (_ \ )   // \/ \/ \/ \/    \/    / / / \ \/ / )( / \/ \(___)( (__(  O )/    / ) _)  )(( (_ \'
echo '(__)  (__\_) \___/(__\_)\_)(_/\_)(_/\_/\_/\_)__)(_/   \__/ (__)\_)(_/      \___)\__/ \_)__)(__)  (__)\___/'
echo ''
echo ''

echo "Installing Prgrmman/vim-config"
echo "Warning, this will remove and overwrite ~/.vimrc and ~/.vimrc. Proceed? [y/n] ?"

read response

echo "$response" | egrep -i "yes|y" > /dev/null
if [[ $? -ne 0 ]]; then
  printf "Cancelling install"
  exit 0
fi



if [ -d "$VIMDIR" ]; then
  printf "\nRemoving $VIMDIR"
  rm -rf $VIMDIR
  printf "...done\n"
fi

if [ -f "$VIMRC" ]; then
  printf "\nRemoving $VIMRC"
  rm -f $VIMRC
  printf "...done\n"
fi

printf "\nCopying files"
cp .vimrc $VIMRC
cp -r vim $VIMDIR
printf "...done\n"

# TODO make an offline plugin sync option
if [ $useOffline = true ]; then
  cp offline/plugged.zip $VIMDIR
  cd $VIMDIR
  unzip plugged.zip
  rm plugged.zip
  cd $WORKINGDIR
  ls
fi

printf "\nOpening vim to install plugins"
vim -c "PlugInstall | qa"
printf "...done\n"
