#!/usr/bin/bash

# This script will overwrite your previous ~/.vimrc and ~/.vim
# Only proceed if this is desired

echo '____  ____   ___  ____  _  _  _  _   __   __ _    _  _  _  __  _  _        ___  __   __ _  ____  __  ___ '
echo '(  _ \(  _ \ / __)(  _ \( \/ )( \/ ) / _\ (  ( \  / )/ )( \(  )( \/ ) ___  / __)/  \ (  ( \(  __)(  )/ __)'
echo ' ) __/ )   /( (_ \ )   // \/ \/ \/ \/    \/    / / / \ \/ / )( / \/ \(___)( (__(  O )/    / ) _)  )(( (_ \'
echo '(__)  (__\_) \___/(__\_)\_)(_/\_)(_/\_/\_/\_)__)(_/   \__/ (__)\_)(_/      \___)\__/ \_)__)(__)  (__)\___/'
echo ''
echo ''


echo "Installing Prgrmman/vim-config"
echo "Warning, this will remove and overwrite ~/.vimrc and ~/.vimr. Proceed? [y/n] ?"

read response

echo "$response" | egrep "yes|y|Y|yes" > /dev/null
if [[ $? -ne 0 ]]; then
  echo "Cancelling install"
  exit 0
fi

VIMDIR=~/.vim
VIMRC=~/.vimrc

if [ -d "$VIMDIR" ]; then
  echo "Removing $VIMDIR"
  rm -rf $VIMDIR
  echo "done"
fi

if [ -f "$VIMRC" ]; then
  echo "Removing $VIMRC"
  rm -f $VIMRC
  echo "done"
fi

echo "Copying files"
cp .vimrc $VIMRC
cp -r . $VIMDIR
echo "done"

echo "Opening vim to install plugins"
vim -c "PlugInstall | sleep 2000m| qa"
echo "done"










