#!/usr/bin/bash

# This script will overwrite your previous ~/.vimrc and ~/.vim
# Only proceed if this is desired

# TODO make an offline plugin sync option

echo '____  ____   ___  ____  _  _  _  _   __   __ _    _  _  _  __  _  _        ___  __   __ _  ____  __  ___ '
echo '(  _ \(  _ \ / __)(  _ \( \/ )( \/ ) / _\ (  ( \  / )/ )( \(  )( \/ ) ___  / __)/  \ (  ( \(  __)(  )/ __)'
echo ' ) __/ )   /( (_ \ )   // \/ \/ \/ \/    \/    / / / \ \/ / )( / \/ \(___)( (__(  O )/    / ) _)  )(( (_ \'
echo '(__)  (__\_) \___/(__\_)\_)(_/\_)(_/\_/\_/\_)__)(_/   \__/ (__)\_)(_/      \___)\__/ \_)__)(__)  (__)\___/'
echo ''
echo ''


echo "Installing Prgrmman/vim-config"
echo "Warning, this will remove and overwrite ~/.vimrc and ~/.vimrc. Proceed? [y/n] ?"

read response
 
echo "$response" | egrep -i "yes|y" > /dev/null
if [[ $? -ne 0 ]]; then
  printf "Cancelling install"
  exit 0
fi

VIMDIR=~/.vim
VIMRC=~/.vimrc

if [ -d "$VIMDIR" ]; then
  printf "\nRemoving $VIMDIR"
  rm -rf $VIMDIR
  printf "...done"\n
fi

if [ -f "$VIMRC" ]; then
  printf "\nRemoving $VIMRC"
  rm -f $VIMRC
  printf "...done\n"
fi

printf "\nCopying files"
cp .vimrc $VIMRC
cp -r . $VIMDIR
printf "...done\n"

printf "\nOpening vim to install plugins"
vim -c "PlugInstall | qa"
printf "...done\n"










