#!/usr/bin/bash

# This script is designed to update changes in vim-config to either git or your local vim files


# Helper functions

function usage {
  echo "Usage: ./update [--git]"
  echo "Desc: updates local vim-config with local changes"
  echo "  use --git to propagate changes to github"
  echo "  Note: this will only work if you have access to the github"
  exit 1
}


### Main code body

if [[ $# -eq 0 ]]; then
  # no arguments print usage message
  usage
fi


# Process args
for i in "$@"
do
  if [[ $i -eq "--git" ]]; then
